### PR TITLE
Adding my website!

### PR DESCRIPTION
**Pull request by imclint21**
Hey

I added our website, HypeProxy.io!

Best regards

### CODE REVIEW

**Comment by Taritsyn** [comment]
Hello, Clint!

Why on your site not using HTML minification?

**Comment by imclint21** [comment]
Because I make a new update that will include minifications! but not present for now ^^

```
⚠️ 05/10/2019 HYPEPROXY.IO v1.1 UPDATE

We just release our new HypeProxy.io version! Including this:

➡️ An Improved Dashboard Design with a lot of realtime charts
➡️ Automatic IP Renew feature
➡️ Real-time Logging
➡️ A Better User Experience (UX)
➡️ Invoices PDF Export and Download
➡️ Fix a lot of bugs and defects

✅ https://www.youtube.com/watch?v=v3w-_i3tNfw
```

**Comment by Taritsyn** [comment]
I will add your site to the list only after I see minified HTML on it.

**Comment by imclint21** [comment]
Sure, no problem!

**Comment by imclint21** [comment]
Hi @Taritsyn, its good now :D

**Comment by Taritsyn** [comment]
Thanks!

**Pull request merged**
